server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: false #提交ip信息
    hostname: eureka
  client:
    register-with-eureka: false #防止向eureka注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
