server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
spring:
  application:
    name: hystrix
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest



#开启熔断  默认false
feign:
  hystrix:
    enabled: true
    #Boot 2.0.x以后的actuator只暴露了info和health2个端点，这里我们把所有端点开放，include: '*'代表开放所有端点。这里开放hystrix断点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
 :
